/*******************************************************************************
**                                                                            **
**      SCORE CONSTANTS                                                       **
**                                                                            **
*******************************************************************************/

DEF NUMBER_OF_HIGH_SCORES   EQU 5

DEF SCORE_BYTES             EQU 3
DEF SCORE_DIGITS            EQU SCORE_BYTES * 2
