/*******************************************************************************
**                                                                            **
**      SOUND CONSTANTS                                                       **
**                                                                            **
*******************************************************************************/

RSRESET
DEF SOUND_CH_1              RB 1 ; $00
DEF SOUND_CH_2              RB 1 ; $01
DEF SOUND_CH_3              RB 1 ; $02
DEF SOUND_CH_4              RB 1 ; $03
DEF NUMBER_OF_CH            RB 0 ; $04

RSRESET
DEF SFX_MENU_A              RB 1 ; $00
DEF SFX_MENU_B              RB 1 ; $01
DEF SFX_JUMP                RB 1 ; $02
DEF SFX_DEAD                RB 1 ; $03
DEF SFX_SCORE               RB 1 ; $04
DEF SFX_SECRET              RB 1 ; $05
DEF NUMBER_OF_SFX           RB 0 ; $06
