/*******************************************************************************
**                                                                            **
**      GAME OVER SPRITE CONSTANTS                                            **
**                                                                            **
*******************************************************************************/

DEF GAME_OVER_Y_POS_0           EQU (SCRN_Y / 2)
DEF GAME_OVER_X_POS_0           EQU (SCRN_X / 2)
DEF GAME_OVER_X_POS_1           EQU (SCRN_X / 2) + META_SPRITE_COL_1_X

DEF GAME_OVER_SPRITE_0          EQUS "wShadowOAM.38"
DEF GAME_OVER_SPRITE_1          EQUS "wShadowOAM.39"

DEF GAME_OVER_SPRITE_0_TILE     EQU $7C
DEF GAME_OVER_SPRITE_1_TILE     EQU $7E
